CDP Support for GraphQL Plan Requests
ibi-group/otp-middleware pull request #178
Opened 2022-11-16 20:15 UTC by miles-grant-ibigroup

…equests

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_

### Description

The current CDP only supports queries which are made via the `/plan` REST endpoint. To read graphQL queries we need to read those. This PR adds support for doing so. 

Introduces a new `OTP_GRAPHQL_ENDPOINT` config parameter which can probably be left at the default.

2022-11-23 10:05 UTC, br648 requested changes
SonarLint (https://plugins.jetbrains.com/plugin/7973-sonarlint) has picked up most of these comments. It is worth installing. 

Apart from that, I was going to suggest added a test or two to cover this refacor, but I can't see any original tests in this area, so not so sure! Add a test if you think it would be beneficial.

2022-11-23 10:05 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                Map graphQlVariables = (Map) getPOJOFromJSON(requestBody, Map.class).get("variables");
Repalce `Map` with `HashMap`.

2022-11-23 10:05 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                String randomBatchId = Integer.toString((int) (Math.random() * 1_000_000_000), 36);
Replace `Math.random()` with `Random.nextInt()`

2022-11-23 10:05 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                LOG.warn("Invalid GraphQL Request received. Still passing to OTP2: " + e.getMessage());
Don't use String concat, use `LOG.warn("message {}", e.getMessage());`

2022-11-23 10:05 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                LOG.warn("Failed to read variables from GraphQL Plan request. Still passing to OTP2: " + e.getMessage());
Don't use String concat, use LOG.warn("message {}", e.getMessage());

2022-11-23 10:05 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +        return handlePlanTripResponse(request.queryParams("batchId"), request.queryParams("fromPlace"), request.queryParams("toPlace"), otpDispatcherResponse, otpUser);
Put each param on it's own line to aid readability.

2022-11-23 10:05 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +    private static boolean handlePlanTripResponse(String batchId, String fromPlace, String toPlace, OtpDispatcherResponse otpDispatcherResponse, OtpUser otpUser) {
Add new line between methods. Put each param on it's own line to aid readability.

2022-11-23 13:17 UTC, miles-grant-ibigroup commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                String randomBatchId = Integer.toString((int) (Math.random() * 1_000_000_000), 36);
I tried this but it didn't behave correctly!

2022-11-28 15:49 UTC, br648 approved these changes
LGTM

2022-11-29 04:26 UTC, daniel-heppner-ibigroup approved these changes
This all looks good, will be interesting to see how it works with the new GraphQL queries! One  thing that we might consider is that OTP supports a `from` and `to` field in addition to `fromPlace` and `toPlace`. These use a different format and contain just the lat/lng. I don't think we will ever use this in OTP-RR, though.

2022-11-29 13:32 UTC, miles-grant-ibigroup commented
Good to know thanks! If in the future we ever use this we can always add more parsing and make it configurable what's enabled and what's not

2022-11-29 13:32 UTC, merged