feat(MonitoredTripController): add support for otp2 to checkItinerary
ibi-group/otp-middleware pull request #182
Opened 2023-03-16 22:36 UTC by daniel-heppner-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR adds OTP2 support to the checkItinerary endpoint. It does this with a new query parameter added to the URL to specify the OTP version.

2023-03-16 23:04 UTC, daniel-heppner-ibigroup commented
I am open to better ways to do this, I am not very familiar with the code base as a whole. We could also add otp version to the config since I don't believe we'll ever have a middleware instance being used by two different versions at the same time. 

Also, we will eventually need to upgrade this to use GraphQL and improve the accuracy of this endpoint. This is just a stopgap so there's no regression when we move to OTP2.

2023-03-21 08:41 UTC, br648 requested changes
A few minor changes. Overall I think this is the best approach over using a config value.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/MonitoredTripController.java
> +import io.github.manusant.ss.descriptor.ParameterDescriptor;
Remove unused import.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Remove unused import.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +            default:
`default` clause should be at the end of the `switch` statement for readability. `case 1:` will obvs have to move as well.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +    public static OtpVersion getOtpVersionFromRequest(Request request) {
Add method comment.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/utils/ConfigUtils.java
> +    /** * Returns true if the given config has the requested property.
Revert this change.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +    public static OtpVersion intToVersion(int versionAsInt) {
Change the method to `private`. Consider changing this method name to `getOtpVersion` and the parameter to `int version`.

2023-03-21 08:41 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +            logMessageAndHalt(request, HttpStatus.BAD_REQUEST_400, "Error parsing otpVersion parameter", e);
Nit. Full stop.

2023-03-24 07:12 UTC, br648 approved these changes
Thanks for the changes. All good.

2023-03-24 20:15 UTC, miles-grant-ibigroup requested changes
I'm confused -- is this adding OTP2 support? I see that OTP2 as a version is being passed through correctly, but I'm not seeing what we're doing with that new field?

I'm also not entirely sold on using a url parameter to decide whether to use otp1 or otp2. Wouldn't this maybe make more sense as a config parameter? Do we expect one middleware to handle both at once?

2023-03-24 20:15 UTC, miles-grant-ibigroup commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +            case 2:
Don't we have an enum we can use here instead?

2023-03-24 20:15 UTC, miles-grant-ibigroup commented on src/main/java/org/opentripplanner/middleware/controllers/api/MonitoredTripController.java
> +                    .withQueryParam().withName("otpVersion").withDefaultValue("1").and()
Can we use the enum here too?

2023-03-24 20:15 UTC, miles-grant-ibigroup commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +            return getOtpVersion(Integer.parseInt(request.queryParamOrDefault("otpVersion", "1")));
Can we use the enum here as well?

2023-03-24 23:34 UTC, daniel-heppner-ibigroup commented on src/main/java/org/opentripplanner/middleware/otp/OtpVersion.java
> +            case 2:
I am not sure what you mean. The problem is that the value coming from the API is an int.

2023-03-24 23:41 UTC, daniel-heppner-ibigroup commented
> I'm also not entirely sold on using a url parameter to decide whether to use otp1 or otp2. Wouldn't this maybe make more sense as a config parameter? Do we expect one middleware to handle both at once?

@miles-grant-ibigroup That's what I was referring to with this. I'll look into doing it in the config instead of with qp.

> I am open to better ways to do this, I am not very familiar with the code base as a whole. We could also add otp version to the config since I don't believe we'll ever have a middleware instance being used by two different versions at the same time.

2023-03-27 21:36 UTC, miles-grant-ibigroup requested changes
Still unclear as to what the OTP2 parameter is actually doing -- what change does it make if you set it to OTP2? Also I wouldn't name the configuration key OTP_VERSION, since both are actively supported at the same time.

Finally, it's a nitpick but would it be possible to replace all `"1"` and `"2"` with `OtpVersion.OTP1`/`OtpVersion.OTP2`?

2023-03-28 22:53 UTC, daniel-heppner-ibigroup commented
> since both are actively supported at the same time.

I made this change because you said:

> Wouldn't this maybe make more sense as a config parameter? Do we expect one middleware to handle both at once?

I think at this point I'm as confused as you are.

2023-03-28 23:00 UTC, closed without merging