Support GraphQL Trip Requests (better PR)
ibi-group/otp-middleware pull request #245
Opened 2024-08-01 14:51 UTC by binh-dam-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

Supersedes #244, and does no longer includes changes from #219.
This PR adds support for recording trip requests made from the GraphQL endpoint.

2024-08-02 21:24 UTC, JymDyerIBI commented on src/main/java/org/opentripplanner/middleware/connecteddataplatform/AnonymizedTripRequest.java
> +     * @return A list of strings, and at a minimum, a list with one element which is an empty string.
Really good comment to have here!

2024-08-02 21:40 UTC, JymDyerIBI approved these changes
Looks good to me!

2024-08-05 13:04 UTC, br648 requested changes
A few minor points. Also, I just need to understand if we are committing to just OTP2 and if we are should all tests related to OTP1 be updated to OTP2 or removed?

2024-08-05 13:04 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/connecteddataplatform/AnonymizedTripRequest.java
> +        QueryVariables queryVariables = tripRequest.otp2QueryParams;
Does this mean we are committing to OTP2 only once merged? Is that a wider goal anyway?

2024-08-05 13:04 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                    queryVariables.fromPlace,
Consider creating a second constructor which takes just `QueryVariables`.

2024-08-05 13:04 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/models/TripRequest.java
> +    public Map<String, String> requestParameters;
This parameter is only referenced in the `toString()` method, as far as I can tell, and can probably be removed.

2024-08-05 13:04 UTC, br648 commented on src/test/java/org/opentripplanner/middleware/testutils/OtpTestUtils.java
> +    public static final OtpDispatcherResponse OTP2_DISPATCHER_PLAN_RESPONSE =
Could all of the OTP1 tests be removed?

2024-08-05 13:14 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/connecteddataplatform/AnonymizedTripRequest.java
> +        QueryVariables queryVariables = tripRequest.otp2QueryParams;
Correct, the OTP1 REST API will be removed very soon.

2024-08-05 13:15 UTC, binh-dam-ibigroup commented on src/test/java/org/opentripplanner/middleware/testutils/OtpTestUtils.java
> +    public static final OtpDispatcherResponse OTP2_DISPATCHER_PLAN_RESPONSE =
Let me see if some of the OTP1 tests can be removed. This PR is a partial migration as its title suggests.

2024-08-05 14:56 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/controllers/api/OtpRequestProcessor.java
> +                    queryVariables.fromPlace,
Good call, refactored in https://github.com/ibi-group/otp-middleware/pull/245/commits/b72f397fe0022b84a4886b109438c967357c39f3.

2024-08-05 14:59 UTC, binh-dam-ibigroup commented on src/test/java/org/opentripplanner/middleware/testutils/OtpTestUtils.java
> +    public static final OtpDispatcherResponse OTP2_DISPATCHER_PLAN_RESPONSE =
Actually, for this PR, code regarding itinerary existence checking is unchanged, and that code still uses OTP1. The migration for itinerary existence and trip monitoring is handled in #243.

2024-08-05 15:06 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/models/TripRequest.java
> +    public Map<String, String> requestParameters;
Yep, I went ahead and removed in https://github.com/ibi-group/otp-middleware/pull/245/commits/fe38a33b34a6507d0db5cd7e2177e0ec762ab26c.

2024-08-05 15:42 UTC, br648 approved these changes
Great. This looks good now.

2024-08-05 15:49 UTC, merged

2024-08-12 17:59 UTC, JymDyerIBI reviewed
Changes look good.