Provide traveler with continue instruction
ibi-group/otp-middleware pull request #268
Opened 2024-11-13 13:59 UTC by br648

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Provide a "continue on street" reassurance instruction when the traveler is on track, but no immediate instruction is available.

2024-11-14 19:10 UTC, binh-dam-ibigroup requested changes
Can you address the wrong street name, and put back literals in the tests, please.

2024-11-14 19:10 UTC, binh-dam-ibigroup commented on src/test/java/org/opentripplanner/middleware/controllers/api/TrackedTripControllerTest.java
> -                "IMMEDIATE: Head WEST on Adair Avenue Northeast",
I think we'll need the plain text to keep track of the kinds of instructions expected. Or, we can further break down the instructions, this one could be a "directional" instruction for instance.

2024-11-14 19:10 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/triptracker/instruction/ContinueInstruction.java
> +        if (isNotEmpty(legStep) && isNotEmpty(legStep.streetName)) {
For objects, can we use `!= null` and for strings, `Strings.isBlank` (or what is the rationale for pulling in a new library)?

2024-11-14 19:10 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/triptracker/TravelerLocator.java
> +            Step currentStep = isPositionPastStep(travelerPosition, nextStep)
At times, this piece produces the incorrect street name. I'll  send an example where the behavior is not what you/d expect.

2024-11-20 14:53 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/triptracker/instruction/ContinueInstruction.java
> +        if (isNotEmpty(legStep) && isNotEmpty(legStep.streetName)) {
Updated: https://github.com/ibi-group/otp-middleware/pull/268/commits/6a1a94ab4b6f8ac32448c66db5b572cbeaf942c0

2024-11-20 15:00 UTC, br648 commented on src/test/java/org/opentripplanner/middleware/controllers/api/TrackedTripControllerTest.java
> -                "IMMEDIATE: Head WEST on Adair Avenue Northeast",
It would be cleaner to further break down the instruction. Also, this way eliminates time zone issues. But I think that is out of scope. Let me know.

2024-11-20 15:02 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/triptracker/TravelerLocator.java
> +            Step currentStep = isPositionPastStep(travelerPosition, nextStep)
I've reworked this. Seems to work ok now with the example you provided.

2024-11-22 19:31 UTC, binh-dam-ibigroup approved these changes
Thanks for the fixes!

2024-12-09 16:51 UTC, JymDyerIBI approved these changes
This looks good.

2024-12-09 18:52 UTC, merged