OTP-1465 Schedule Trip History Uploade
ibi-group/otp-middleware pull request #272
Opened 2024-11-22 21:01 UTC by JymDyerIBI

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [] All tests and CI builds passing

### Description

OTP-1465: Schedule initial trip history upload at 3:00 AM instead of right away. Utility method finds next occurrence of 3:00 AM (or any time of day), which will be today or tomorrow, and scheduler is invoked with an initial delay to that time.

A new `CONNECTED_DATA_PLATFORM_TRIP_HISTORY_UPLOAD_START_TIME` configuration setting is introduced with a default value of `"03:00"`.

Some OTP-1444 code was written concurrently, a different upload/transfer job. This same code could be used for that, but the two branches would need to be merged.

2024-11-27 15:12 UTC, binh-dam-ibigroup requested changes
Sorry, I should have mentioned that hourly uploads are not subject to the 3am start.

2024-11-27 15:12 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/connecteddataplatform/ConnectedDataManager.java
> +            long initialDelayMinutes = Duration.between(now, startAt).toMinutes();
One detail that I overlooked is that the configured start time should only apply if the uploads are daily (`CONNECTED_DATA_PLATFORM_REPORTING_INTERVAL = "daily"`). If the reporting interval is hourly, the job should still start immediately.

2024-11-27 15:12 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/connecteddataplatform/ConnectedDataManager.java
> +            long initialDelayMinutes = Duration.between(now, startAt).toMinutes();
Extract a method to compute the initial delay (lines 122 to 125), and place it in `DateTimeUtils` or `Scheduler`, and add a unit test for that method.

2024-11-27 15:12 UTC, binh-dam-ibigroup commented on src/test/java/org/opentripplanner/middleware/utils/DateTimeUtilsTest.java
> +        assertTrue(zdtNext.isAfter(zdt));
Since you are using an absolute date `zdt`, can you assert on the date, hour, and minutes instead?

2025-03-26 20:55 UTC, JymDyerIBI commented on src/main/java/org/opentripplanner/middleware/connecteddataplatform/ConnectedDataManager.java
> +            long initialDelayMinutes = Duration.between(now, startAt).toMinutes();
I've made these changes. At first I had the new `Scheduler` method accept a `java.util.concurrent.TimeUnit` argument and return a unit-specific value, but that got complicated since `TemporalUnit`/`ChronoUnit` conversions are arbitrarily supported. So now it just returns the initial delay in millis and the new unit tests are simplified accordingly.

2025-03-26 21:05 UTC, JymDyerIBI commented on src/test/java/org/opentripplanner/middleware/utils/DateTimeUtilsTest.java
> +        assertTrue(zdtNext.isAfter(zdt));
This is now pushed.

2025-03-26 21:24 UTC, JymDyerIBI commented
Note: The Maven CI test has failed with every push, but succeeds when I rerun it.

2025-03-27 17:05 UTC, binh-dam-ibigroup approved these changes
Thank you, that works!

2025-03-31 07:43 UTC, br648 approved these changes
Good update! Just a couple of minor items to address.

2025-03-31 07:43 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/utils/Scheduler.java
> +     * Calcluate an initial delay in milliseconds precision, until a start time specified as text
Typo `Calculate`.

2025-03-31 07:43 UTC, br648 commented on src/test/java/org/opentripplanner/middleware/utils/DateTimeUtilsTest.java
> +        assertEquals(zdtNext.getMinute(), 15);
There three assertions are around the wrong way.

2025-03-31 15:20 UTC, JymDyerIBI commented on src/main/java/org/opentripplanner/middleware/utils/Scheduler.java
> +     * Calcluate an initial delay in milliseconds precision, until a start time specified as text
Fixed in https://github.com/ibi-group/otp-middleware/pull/272/commits/5def5aa8b6289e2cb421792350c8950e0c8489ff

2025-03-31 15:20 UTC, JymDyerIBI commented on src/test/java/org/opentripplanner/middleware/utils/DateTimeUtilsTest.java
> +        assertEquals(zdtNext.getMinute(), 15);
Fixed in https://github.com/ibi-group/otp-middleware/pull/272/commits/57b6fdad655a7b7fce059f3e556b7861f0f64c06

2025-03-31 15:27 UTC, merged