Aws sdk integration
ibi-group/otp-middleware pull request #30
Opened 2020-06-12 17:28 UTC by landonreed

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

TODO

2020-06-23 13:53 UTC, br648 submitted a review, later dismissed
Just a couple of methods that need comments. The rest looks good, in particular registering the spark end point within the controller. Perhaps we should be doing that with all the controllers?

2020-06-23 13:53 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +    public static void register (Service spark, String apiPrefix) {
Method comment

2020-06-23 13:53 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +    public static List<GetUsageResult> getUsageLogs(Request req, Response res) {
Method comment

2020-06-24 21:22 UTC, binh-dam-ibigroup reviewed
I need to understand how the log requests work without us passing the API gateway key to AWS.

2020-06-24 21:22 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +        spark.get(apiPrefix + "/secure/logs", LogController::getUsageLogs, JsonUtils::toJson);
A reminder for us to discuss the API documentation (it is currently embedded in the endpoint definition for `ApiController` subclasses).

2020-06-24 21:22 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +        apiKeys.getItems();
Do we intend to use any of the `apiKeys`? If not, remove these lines.

2020-06-24 21:22 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +        apiKeys.getItems();
The broader question for this and your TODO comment @landonreed is how is the API key passed to AWS?

2020-06-26 07:27 UTC, evansiroky commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk -->
Can you add some more comments about what these are used for?

2020-06-26 07:31 UTC, evansiroky requested changes
See comment and thumbs up on others' comments.

2020-07-06 14:17 UTC, landonreed commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +        apiKeys.getItems();
Just added some changes here that removes these unused lines for now and allows filtering on a specific key. As we start work on the third party developer account, we can begin to make this connection a little more clear.

2020-07-08 00:22 UTC, evansiroky approved these changes

2020-07-09 15:19 UTC, binh-dam-ibigroup approved these changes

2020-07-09 15:48 UTC, merged