OpenAPI documentation
ibi-group/otp-middleware pull request #35
Opened 2020-07-13 22:15 UTC by binh-dam-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [na] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [na] All tests and CI builds passing

### Description

This PR makes use of [`swagger-inline`](https://github.com/readmeio/swagger-inline) to generate the API documentation in OpenAPI 3.0 format for all code merged in the `dev` branch as of writing.

`swagger-inline` takes a base OpenAPI file (`api-base.yaml`) and adds contents from documentation snippets inside JavaDoc-style comments inside the source files. The result is a self-contained file `api.json` that you can import to AWS API Gateway.

I tried to keep the documentation snippets as close as the relevant code as possible, however some copy-pasting has been necessary.

This PR does not address automatic documentation generation, although the PR brings us much closer to that stage. 

No changes to existing code are made in this PR.

### To test:

- Install `nodejs`, and `npm` or equivalent package manager.
- Install `swagger-inline` globally: `npm install -y swagger-inline` (this will change when we deal with automated documentation generation).
- From the root directory of your local copy of this repo: execute `swagger-inline "**/*.java" --base api-base.yaml --format .json > api.json`

Please explain the changes you made here and, if not immediately obvious from the code, how they resolve any referenced issues. Be sure to include all issues being resolved and any special configuration settings that are need for the software to run properly with these changes. If merging to master, please also list the PRs that are to be included.

2020-07-14 13:28 UTC, br648 commented
This is probably a Windows thing, but had to install globally to avoid this:

'swagger-inline' is not recognized as an internal or external command, operable program or batch file.

Using this command:

npm install -y **-g** swagger-inline

2020-07-14 14:11 UTC, binh-dam-ibigroup commented
> This is probably a Windows thing, but had to install globally to avoid this:
> 
> 'swagger-inline' is not recognized as an internal or external command, operable program or batch file.
> 
> Using this command:
> 
> npm install -y **-g** swagger-inline

Thanks @br648 it should be `npm install -g`, not `-y`

2020-07-14 14:18 UTC, landonreed reviewed
@binh-dam-ibigroup, this is not really what I was imagining as far as associating the API documentation with the code. It's completely divorced from the Spark endpoints themselves. This really doesn't aid maintenance of the API docs. At this point, it seems better to just maintain everything in a separate file, so that it's not littering up the code.

Also, my thought for integrating the CORS/API key stuff for AWS API Gateway, was that this would be appended outside of the java code because it's not very relevant to the code/APIs themselves.

2020-07-14 14:25 UTC, br648 requested changes
Where this is implemented it does increase the file size quite a bit. I guess that can't be helped?

Once the api.json file is generated I guess it should be deleted/moved and doesn't therefore need adding to .gitignore?

Apart from that, just one minor comment.

2020-07-14 14:25 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +         */
@binh-dam-ibigroup How come this section is not at the top of the file as is the case with other classes which have this?

2020-07-14 14:25 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/controllers/api/LogController.java
> +        /**
Missing comment?:

// Open API documentation for inherited CRUD methods

2020-07-15 19:34 UTC, landonreed commented
Closing following team discussion due to the lack of automation this approach provides. Further work will continue on #37.

2020-07-15 19:34 UTC, closed without merging