Remove old code
ibi-group/otp-middleware pull request #37
Opened 2020-07-14 15:55 UTC by landonreed

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [ ] Code coverage improves or is at 100% _(remove this if not merging to master)_

### Description

- Adds some swagger tests
- Introduces process for tracking/verifying API docs are up-to-date (maintained at `src/main/resources/doc.yaml` and auto-generating API Gateway enhanced documentation (`target/doc-api-gateway.yaml`)

2020-07-15 08:07 UTC, br648 requested changes
Is the doc-api-gateway.yaml file generated manually? If so it's a bit onerous! Ignore this!

I think these files can be removed as well:

org.opentripplanner.middleware.BasicOtpDispatcher
org.opentripplanner.middleware.Const
org.opentripplanner.middleware.WebSocketClient

2020-07-15 08:07 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/OtpMiddlewareMain.java
>  import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
Remove unused imports.

2020-07-15 08:07 UTC, br648 commented on src/main/java/org/opentripplanner/middleware/OtpMiddlewareMain.java
>          spark.get(API_PREFIX + "/secure/triprequests", TripHistoryController::getTripRequests);
Not strictly part of this update, but stands out now that the other items have been removed. For consistency, this should be moved into a register method similar to `LogController.register`.

2020-07-31 22:18 UTC, binh-dam-ibigroup commented
Closing this PR in favor of #47 and #50.

2020-07-31 22:18 UTC, closed without merging